In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [5]:
current = pd.read_csv("50-current-ratio.csv", index_col=0)

In [6]:
current.head()

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,JPM,MA,PG,UNH,DIS,NVDA,HD,PYPL,BAC,VZ,ADBE,CMCSA,NFLX,KO,NKE,MRK,PEP,T,PFE,INTC,CRM,ABT,ORCL,ABBV,CSCO,TMO,AVGO,XOM,ACN,QCOM,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2020-09-30,1.36,2.53,1.11,3.41,5.51,1.64,0.27,1.91,1.48,NaN,0.88,1.86,0.87,0.82,1.32,NaN,NaN,1.38,0.87,1.07,NaN,0.93,1.24,1.13,NaN,1.30,0.93,0.84,1.40,1.66,NaN,1.70,NaN,0.95,NaN,2.93,NaN,0.86,NaN,2.14,NaN,1.26,1.36,1.07,2.08,NaN,0.57,4.24,1.64,1.29
2020-06-30,1.47,2.52,1.18,3.41,6.03,1.25,0.30,1.55,1.25,NaN,0.88,1.95,0.85,0.84,1.34,NaN,NaN,1.38,0.93,0.96,NaN,0.97,1.12,1.09,NaN,1.32,0.97,0.81,1.42,1.98,NaN,1.57,NaN,0.86,NaN,2.62,NaN,0.93,NaN,1.97,NaN,1.14,1.22,0.91,2.20,NaN,0.61,3.92,1.63,1.24
2020-03-31,1.50,2.90,1.08,3.66,4.60,1.24,0.33,1.25,1.31,NaN,0.89,1.87,0.83,0.75,0.94,NaN,NaN,1.39,0.92,0.99,NaN,0.87,0.82,0.87,NaN,1.12,1.10,0.76,1.03,1.74,NaN,1.43,NaN,3.14,NaN,2.32,NaN,0.78,NaN,1.57,NaN,1.01,1.11,1.90,1.32,NaN,0.71,3.49,1.30,1.22
2019-12-31,1.60,2.80,1.10,3.37,4.40,1.14,0.39,1.27,1.26,NaN,0.92,1.42,0.63,0.69,0.80,NaN,NaN,1.43,0.91,0.84,NaN,0.84,0.90,0.76,NaN,1.24,0.86,0.80,0.88,1.40,NaN,1.44,NaN,3.18,NaN,1.92,NaN,0.78,NaN,1.76,NaN,1.07,1.16,0.98,5.19,NaN,0.54,4.13,1.34,1.11
2019-09-30,1.54,2.85,1.10,3.78,4.66,1.08,0.44,1.56,1.26,NaN,0.93,1.39,0.73,0.70,0.90,NaN,NaN,1.43,0.92,0.89,NaN,0.86,0.73,0.92,NaN,1.26,0.95,0.74,0.91,1.20,NaN,1.54,NaN,1.15,NaN,1.80,NaN,0.78,NaN,1.88,NaN,1.12,1.17,0.84,3.43,NaN,0.58,4.34,1.32,1.11

In [7]:
current.tail()

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,JPM,MA,PG,UNH,DIS,NVDA,HD,PYPL,BAC,VZ,ADBE,CMCSA,NFLX,KO,NKE,MRK,PEP,T,PFE,INTC,CRM,ABT,ORCL,ABBV,CSCO,TMO,AVGO,XOM,ACN,QCOM,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2006-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.54,NaN,NaN,NaN,3.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.91,NaN,NaN,NaN,NaN,NaN,1.17,NaN,1.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.18,NaN,NaN,NaN,3.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.13,NaN,NaN,NaN,NaN,NaN,1.19,NaN,1.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.55,NaN,NaN,NaN,2.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.10,NaN,NaN,NaN,NaN,NaN,1.36,NaN,1.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.86,NaN,NaN,NaN,3.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.05,NaN,NaN,NaN,NaN,NaN,1.41,NaN,1.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.51,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.97,NaN,NaN,NaN,NaN,NaN,1.48,NaN,1.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
current.index = pd.to_datetime(current.index)

In [10]:
current.index

DatetimeIndex(['2020-09-30', '2020-06-30', '2020-03-31', '2019-12-31',
               '2019-09-30', '2019-06-30', '2019-03-31', '2018-12-31',
               '2018-09-30', '2018-06-30',
               ...
               '2007-05-31', '2007-02-28', '2006-11-30', '2006-08-31',
               '2006-05-31', '2006-02-28', '2005-11-30', '2005-08-31',
               '2005-05-31', '2005-02-28'],
              dtype='datetime64[ns]', length=191, freq=None)

In [11]:
current.sort_index(ascending=False, inplace=True)

In [12]:
current.head()

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,JPM,MA,PG,UNH,DIS,NVDA,HD,PYPL,BAC,VZ,ADBE,CMCSA,NFLX,KO,NKE,MRK,PEP,T,PFE,INTC,CRM,ABT,ORCL,ABBV,CSCO,TMO,AVGO,XOM,ACN,QCOM,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.48,NaN,NaN,NaN,2.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.17,NaN,NaN,NaN,NaN,NaN,1.45,NaN,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.84,NaN,NaN,NaN,NaN,NaN,3.92,1.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.22,NaN,NaN,NaN,1.59,NaN,1.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.16,NaN,NaN,NaN,NaN
2020-09-30,1.36,2.53,1.11,3.41,5.51,1.64,0.27,1.91,1.48,NaN,0.88,1.86,0.87,0.82,1.32,NaN,NaN,1.38,0.87,1.07,NaN,0.93,1.24,1.13,NaN,1.3,0.93,0.84,1.4,1.66,NaN,1.7,NaN,0.95,NaN,2.93,NaN,0.86,NaN,2.14,NaN,1.26,1.36,1.07,2.08,NaN,0.57,4.24,1.64,1.29
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,NaN,NaN,NaN,2.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.66,NaN,NaN,NaN,NaN,NaN,1.40,NaN,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.79,NaN,NaN,NaN,NaN,NaN,6.09,1.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.15,NaN,NaN,NaN,1.72,NaN,2.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.87,NaN,NaN,NaN,NaN

In [13]:
current = current.loc[:'2010-01-01']

In [18]:
col = current.resample('Q', convention='end').agg('mean').transpose()['2020-09-30']

In [21]:
result = col > 1

In [22]:
result.to_csv("result-current.csv")