In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [3]:
fcf = pd.read_csv("50-fcf.csv", index_col=0)

In [4]:
fcf.head()

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,JPM,MA,PG,UNH,DIS,NVDA,HD,PYPL,BAC,VZ,ADBE,CMCSA,NFLX,KO,NKE,MRK,PEP,T,PFE,INTC,CRM,ABT,ORCL,ABBV,CSCO,TMO,AVGO,XOM,ACN,QCOM,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2005,2275.0,15793.0,529.0,1621.21,NaN,NaN,7251.0,361.36,9321.0,3166.0,-30236.0,190.85,7015.0,3574.0,2326.0,64.94,2780.0,NaN,-13451.0,7061.0,709.51,1214.0,129.85,5612.0,1320.8,6205.8,4204.0,7398.0,12627.0,8980.0,51.56,3839.91,3364.0,NaN,6876.0,243.5,NaN,34299.0,1575.63,2110.0,799.96,11404.0,626.6,2730.0,1102.85,2372.0,-930.0,2362.0,1829.0,3633.0
2006,1563.0,12826.0,486.0,1677.71,NaN,NaN,5624.0,348.00,12093.0,4753.0,-49579.0,555.69,9590.0,5850.0,4668.0,366.81,2903.0,NaN,13761.0,7005.0,816.70,2223.0,220.86,5190.0,1335.8,5785.0,4065.0,7368.0,15544.0,4772.0,72.46,3924.27,4445.0,NaN,7127.0,334.7,NaN,33824.0,2375.77,2568.0,630.46,10510.0,2963.3,2599.6,1420.83,1813.0,-1221.0,4184.0,2565.0,2579.0
2007,4735.0,15532.0,1181.0,3372.57,NaN,NaN,7177.0,345.00,12537.0,4963.0,-110560.0,613.44,10746.0,5006.0,3832.0,441.86,4257.0,NaN,8893.0,9301.0,1308.98,2031.0,233.17,5741.0,1593.5,5988.2,4551.0,16525.0,11473.0,7625.0,89.10,3527.64,5203.0,NaN,8853.0,1327.2,109.0,36615.0,2280.74,2993.0,715.00,8299.0,4104.4,2929.7,1499.24,2406.0,-726.0,3782.0,3242.0,-1612.0
2008,8505.0,18430.0,1364.0,5494.00,NaN,-63.04,5114.0,120.00,12691.0,6662.0,52780.0,242.00,12890.0,3632.0,4123.0,1082.45,2487.0,NaN,1936.0,10319.0,1168.89,4481.0,240.25,5732.0,1489.0,5274.0,4651.0,13979.0,16537.0,5729.0,160.72,5706.90,7312.0,NaN,10821.0,1171.2,148.0,40407.0,2493.72,2161.0,655.00,9966.0,6374.1,3781.5,1666.33,2976.0,-1833.0,2567.0,2960.0,5937.0
2009,9015.0,15918.0,2920.0,8506.00,122.0,-92.71,10909.0,252.00,14360.0,12362.0,122797.0,1238.00,12768.0,4886.0,3566.0,-158.31,3828.0,NaN,127491.0,14518.0,998.20,5164.0,279.13,6297.0,1313.0,1931.0,4726.0,17851.0,15382.0,6655.0,168.50,6186.11,7726.0,5054.77,8892.0,1472.6,82.0,5947.0,2921.41,6411.0,849.00,-470.0,3588.2,3798.9,1630.41,3380.0,-1543.0,1890.0,3368.0,3743.0

In [5]:
fcf = fcf.transpose()

In [7]:
fcf.head()

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
AAPL,2275.00,1563.00,4735.00,8505.0,9015.0,16590.0,33269.0,42561.0,45501.0,50142.0,70019.0,53497.0,51774.0,64121.0,58896.0,73365.0
MSFT,15793.00,12826.00,15532.00,18430.0,15918.0,22096.0,24639.0,29321.0,24576.0,27017.0,23724.0,24982.0,31378.0,32252.0,38260.0,45234.0
AMZN,529.00,486.00,1181.00,1364.0,2920.0,2516.0,2092.0,395.0,2031.0,1949.0,7450.0,10466.0,8307.0,19400.0,25825.0,NaN
GOOG,1621.21,1677.71,3372.57,5494.0,8506.0,7063.0,11127.0,13346.0,11301.0,12065.0,16657.0,26064.0,23907.0,22832.0,30972.0,NaN
FB,NaN,NaN,NaN,NaN,122.0,405.0,943.0,377.0,2860.0,5495.0,7797.0,11617.0,17483.0,15359.0,21212.0,NaN

In [8]:
fcf['10Y CAGR'] = (fcf[2019]/fcf[2009])**(1/10) - 1

In [9]:
fcf['5Y CAGR'] = (fcf[2019]/fcf[2014])**(1/5) - 1

In [10]:
fcf['1Y CAGR'] = (fcf[2019]/fcf[2018])**(1/1) - 1

In [11]:
fcf.head()

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,10Y CAGR,5Y CAGR,1Y CAGR
AAPL,2275.00,1563.00,4735.00,8505.0,9015.0,16590.0,33269.0,42561.0,45501.0,50142.0,70019.0,53497.0,51774.0,64121.0,58896.0,73365.0,0.206457,0.032706,-0.081487
MSFT,15793.00,12826.00,15532.00,18430.0,15918.0,22096.0,24639.0,29321.0,24576.0,27017.0,23724.0,24982.0,31378.0,32252.0,38260.0,45234.0,0.091656,0.072066,0.186283
AMZN,529.00,486.00,1181.00,1364.0,2920.0,2516.0,2092.0,395.0,2031.0,1949.0,7450.0,10466.0,8307.0,19400.0,25825.0,NaN,0.243557,0.676663,0.331186
GOOG,1621.21,1677.71,3372.57,5494.0,8506.0,7063.0,11127.0,13346.0,11301.0,12065.0,16657.0,26064.0,23907.0,22832.0,30972.0,NaN,0.137953,0.207503,0.356517
FB,NaN,NaN,NaN,NaN,122.0,405.0,943.0,377.0,2860.0,5495.0,7797.0,11617.0,17483.0,15359.0,21212.0,NaN,0.675028,0.310155,0.381079

In [12]:
data = fcf[['10Y CAGR', '5Y CAGR', '1Y CAGR']]

In [16]:
data.sort_values('1Y CAGR', ascending=False)

       10Y CAGR   5Y CAGR     1Y CAGR
MDT    0.056804  0.051773    0.624170
BAC   -0.069889  0.149395    0.563183
KO     0.040822  0.021864    0.484906
FB     0.675028  0.310155    0.381079
GOOG   0.137953  0.207503    0.356517
MCD    0.044646  0.067888    0.340721
AMZN   0.243557  0.676663    0.331186
MA     0.196665  0.193925    0.303550
T      0.050561  0.235878    0.279680
CRM    0.324654  0.372100    0.271779
NKE    0.138027  0.175000    0.218233
UNH    0.128672  0.202256    0.200879
MRK    0.178361  0.083582    0.199831
COST   0.147406  0.110202    0.197148
INTC   0.097883  0.104243    0.188127
MSFT   0.091656  0.072066    0.186283
CSCO   0.053287  0.057699    0.159258
ACN    0.075122  0.137180    0.114737
AVGO   0.605882  0.649470    0.102428
NFLX        NaN  1.260207    0.100171
HON    0.061214  0.087881    0.085394
NVDA        NaN  0.390330    0.079698
PG    -0.003816  0.028329    0.076189
ADBE   0.149688  0.287322    0.070321
JNJ    0.049063  0.033863    0.066670
TMO    0.107362  0.127446    0.064668
CMCSA  0.109326  0.089772    0.046983
HD     0.107521  0.109325    0.044004
VZ     0.020630  0.057885    0.007126
ABBV   0.097124  0.341748   -0.001329
BRK.A  0.076067  0.061805   -0.006780
V      0.471903  0.125766   -0.015954
DHR    0.073990  0.002171   -0.033645
TXN    0.119272  0.088819   -0.038734
WMT    0.037873  0.105270   -0.039434
ORCL   0.052527 -0.021093   -0.055604
AAPL   0.206457  0.032706   -0.081487
ABT   -0.031365  0.116030   -0.083163
PEP    0.016877 -0.063644   -0.108505
LLY    0.005823  0.028073   -0.118501
PYPL        NaN  0.175231   -0.169204
CVX         NaN       NaN   -0.215619
PFE   -0.038272 -0.081013   -0.244686
QCOM   0.002864 -0.031427   -0.464181
JPM   -0.260006 -0.302388   -0.573835
UPS   -0.046542 -0.076029   -0.640526
XOM   -0.010431 -0.151334   -0.674270
DIS   -0.110316 -0.297348   -0.887284
NEE    0.013188  0.077696   -1.781430
TSLA        NaN       NaN -360.333333

In [17]:
data.to_csv("result-fcf.csv")