In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("result-full.csv", index_col=0, header=[0, 1])

In [3]:
data.head()

            DE Current   ROI   Revenue                           EPS  \
     D/E ratio Current  Mean  10Y CAGR   5Y CAGR   1Y CAGR  10Y CAGR
AAPL      True    True  True  0.197500  0.073149 -0.020411  0.249570
MSFT      True    True  True  0.079727  0.077033  0.140295  0.120633
AMZN      True    True  True  0.276040  0.258135  0.204541  0.274174
GOOG      True    True  True  0.212071  0.196510  0.183001  0.170196
FB        True    True  True  0.569994  0.414929  0.266109  0.516426

                              BVPS                           FCF            \
       5Y CAGR   1Y CAGR  10Y CAGR   5Y CAGR   1Y CAGR  10Y CAGR   5Y CAGR
AAPL  0.130280 -0.003356  0.075461 -0.063686 -0.243615  0.206457  0.032706
MSFT  0.139827  1.375587  0.115237  0.109523  0.174226  0.091656  0.072066
AMZN       NaN  0.142502  0.277432  0.441417  0.444376  0.243557  0.676663
GOOG  0.190352  0.124943       NaN  0.131984  0.113328  0.137953  0.207503
FB    0.423520 -0.150594       NaN  0.229220  0.254098  0.675028  0.310155


       1Y CAGR
AAPL -0.081487
MSFT  0.186283
AMZN  0.331186
GOOG  0.356517
FB    0.381079

In [4]:
data.to_excel("data.xlsx")

In [7]:
writer = pd.ExcelWriter("data2.xlsx", engine='xlsxwriter')
data.to_excel(writer, sheet_name='Main')

workbook = writer.book
worksheet = writer.sheets['Main']

# Create a format for a green cell
green_cell = workbook.add_format({
    'bg_color': '#C6EFCE',
    'font_color': '#006100'
})

# Create a format for a red cell
red_cell = workbook.add_format({
    'bg_color': '#FFC7CE',                            
    'font_color': '#9C0006'
})

# Create a conditional formatted of type formula
worksheet.conditional_format('B4:D53', {
    'type': 'cell',                                    
    'criteria': '=',
    'value': True,
    'format': green_cell
})

# Create a conditional formatted of type formula
worksheet.conditional_format('B4:D53', {
    'type': 'cell',                                    
    'criteria': '=',
    'value': False,
    'format': red_cell
})

# Create a conditional formatted of type formula
worksheet.conditional_format('E4:P53', {
    'type': 'cell',                                    
    'criteria': '>=',
    'value': 0.1,
    'format': green_cell
})

# Create a conditional formatted of type formula
worksheet.conditional_format('E4:P53', {
    'type': 'cell',                                    
    'criteria': '<',
    'value': 0.1,
    'format': red_cell
})

writer.close()